openapi: 3.0.0
info:
  title: TVGuide Demo API
  version: 0.0.3

servers:
  - url: https://demo-c.cdn.vmedia.ca/json/
    description: TVGuide Demo server
paths:
  '/Channels':
    get:
      summary: Get list of Channels
      tags:
        - Channels
      operationId: getAllChannels
      responses:
        '200':
          description: Success responce with list of Channels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Channel'
              example:
                - orderNum: 10
                  accessNum: 10
                  CallSign: "W"
                  id: 302719
                - orderNum: 29
                  accessNum: 29
                  CallSign: "SSC"
                  id: 302735
        default:
          description: unexpected behaviour

  '/ProgramItems':
    get:
      summary: Get list of ProgramItems
      tags:
        - ProgramItems
      operationId: getProgramItems
      responses:
        '200':
          description: Success responce with list ProgramItems
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProgramItem'
              example:
                - startTime: '2020-07-09T01:30:00Z'
                  recentAirTime:
                    id: 30717891
                    channelID: 302735
                  length: 150
                  name: 'Jesse James'
                - startTime: "2020-07-09T02:00:00Z"
                  recentAirTime:
                    id: 30714553
                    channelID: 302719
                  length: 120
                  name: "Christmas in Homestead"
        default:
          description: unexpected behaviour

components:
  schemas:
    Channel:
      type: object
      properties:
        orderNum:
          type: integer
          format: int64
          minimum: 1
          example: 1
        accessNum:
          type: integer
          format: int64
          minimum: 1
          example: 1
        CallSign:
          type: string
          example: CIIIDT
        id:
          type: integer
          format: int64
          example: 302714
      required:
        - orderNum
        - accessNum
        - CallSign
        - id
      example:
        orderNum: 1
        accessNum: 1
        CallSign: "CIIIDT"
        id: 302714

    RecentAirTime:
      description: Class to join programs and channels
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 30717891
        channelID:
          type: integer
          format: int64
          example: 302735
      required:
        - id
        - channelID
      example:
        id: 30717891
        channelID: 302735

    ProgramItem:
      description: Class describes Program Guide item
      type: object
      properties:
        startTime:
          type: string
          format: date-time
          example: "2020-07-09T01:30:00Z"
        recentAirTime:
          $ref: '#/components/schemas/RecentAirTime'
        length:
          type: integer
          format: int64
          example: 120
        name:
          type: string
          example: 'Christmas in Homestead'
      required:
        - startTime
        - recentAirTime
        - length
        - name
      example:
        startTime: "2020-07-09T01:30:00Z"
        recentAirTime:
          id: 30717891
          channelID: 302735
        length: 150
        name: 'Jesse James'
